- name: create group and user accounts
  hosts: webservers
  tasks:
    - name: create group
      group:
        name: itadmins
        state: present
    - name: create users
      user:
        name: "{{ item }}"
        state: present
        groups: itadmins
      loop:
        - it2
        - it3
        - it4