- name: create group and user accounts
  hosts: dc
  vars_files:
    - 16userlistpass.txt
      #- 14userlist2.txt
    #vars:
      #users:
      #  - it11
      #  - 1t12
      #  - it13
  tasks:
    - name: create group
      group:
        name: itadmins
        state: present
    - name: create users
      user:
        name: "{{ item.un }}"
        comment: "{{ item.ucomment }}"
        shell: "{{ item.ushell }}"
        password: "{{ item.upass | password_hash('sha512') }}"
        #password: "{{ item.upass }}" #not suggested
        state: present
        groups: itadmins
      loop: "{{ users }}"
        #- it2
        #- it3
        #- it4
