- name: Get Free mem and save in /tmp
  hosts: dc
  tasks:
    - name: free space command
      shell: free -h 
      register: mem
    - name: use debug
      ansible.builtin.debug:
        var: mem
    - name: write to file /temp
      copy: 
         content: "{{mem.stdout}}"
         dest: /tmp/memfree.txt
